"""
Django settings for chronomoment project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3x&%^^2dc3zs2chnt&r98()$%l&s&&%=+-)i5!*8b&!z+92dbd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'register.apps.RegisterConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chronomoment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chronomoment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add your custom authentication backend
# The path should be 'your_app_name.backends.OrganiserBackend'
# Make sure to keep 'django.contrib.auth.backends.ModelBackend' if you want
# to use Django's default User model (e.g., for Django Admin).
AUTHENTICATION_BACKENDS = [
    'main.backends.OrganiserBackend', # Your custom backend
    'django.contrib.auth.backends.ModelBackend', # Django's default
]

# Optional: Tell Django what model your custom backend is managing users for
# This is mainly for internal Django mechanisms and some third-party apps.
# It doesn't replace the need for the custom backend for email login.
AUTH_USER_MODEL = 'main.Organisers' # Use this if Organisers is your ONLY user model

# Set the URL where Django will redirect users who are not logged in
# (e.g., for @login_required decorator)
LOGIN_URL = '/login/' # Or whatever your login URL name is, e.g., 'login'

# URL to redirect after successful login (if not specified elsewhere)
LOGIN_REDIRECT_URL = '/home/' # Or your actual home/dashboard URL

# URL to redirect after logout
LOGOUT_REDIRECT_URL = '/login/' # Or where you want users to go after logout



# Email Configuration for Development (prints emails to your console)
# This is ideal for testing during development as it doesn't require a real SMTP server.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# This email address will appear as the sender of the invitation emails.
EMAIL_HOST_USER = 'demirtanriver@gmail.com' 

# For a production environment, you would typically use an SMTP backend
# provided by an email service (e.g., SendGrid, Mailgun, AWS SES, Gmail SMTP).
# Example for a real SMTP setup (uncomment and configure when deploying):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com' # Replace with your SMTP host
# EMAIL_PORT = 587 # Common port for TLS
# EMAIL_USE_TLS = True # Use TLS for secure connection
# EMAIL_HOST_USER = 'your_smtp_username' # Your SMTP username
# EMAIL_HOST_PASSWORD = 'your_smtp_password' # Your SMTP password

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # This will create a 'media' folder in your project root
