# chronomoment/settings.py

"""
Django settings for chronomoment project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-3x&%^^2dc3zs2chnt&r98()$%l&s&&%=+-)i5!*8b&!z+92dbd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.elasticbeanstalk.com',
    '.amazonaws.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'register.apps.RegisterConfig',
    'storages', # ADDED: Required for django-storages (AWS S3 integration)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chronomoment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', 
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chronomoment.wsgi.application'


# Database
# Using PostgreSQL for production. Remember to install psycopg2-binary.
# For local development, you might use SQLite initially, but switch to PostgreSQL for deployment.
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3', # <-- CHANGED: Use SQLite engine
#         'NAME': BASE_DIR / 'db.sqlite3',        # <-- CHANGED: Point to your local SQLite file
#     }
# }

# Database configuration using environment variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'demir'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '85321Gemoment8.'),
        'HOST': os.environ.get('DB_HOST', 'gemomentdatabase.cr26ey8gmw69.eu-north-1.rds.amazonaws.com'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC' # Recommended to store all times in UTC for consistency

USE_I18N = True

USE_TZ = True # Keep this as True for timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # ADDED: For Django's collectstatic command


# Media files (user uploads) - Configuration for AWS S3
# These settings will override MEDIA_ROOT and MEDIA_URL for file storage if DEFAULT_FILE_STORAGE is S3.
# MEDIA_ROOT and MEDIA_URL (local) are effectively ignored when S3 is the default.
# You can keep them for local development fallback if DEFAULT_FILE_STORAGE is not S3,
# but they are not used when S3 is active.
# MEDIA_URL = '/media/' # This local MEDIA_URL is overridden by S3 config below
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # This local MEDIA_ROOT is overridden by S3 config below


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'main.Organisers' # Your custom user model

# Login/Logout URLs
LOGIN_URL = '/login/' # Your login URL
LOGIN_REDIRECT_URL = '/home/' # Your actual home/dashboard URL after login
LOGOUT_REDIRECT_URL = '/login/' # Where users go after logout


# Email Configuration - Development vs Production
if DEBUG:
    # Development: Print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'demirtanriver@gmail.com')
else:
    # Production: Use SMTP backend
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'demirtanriver@gmail.com')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')


# --- AWS S3 Settings for Media Files ---
# Using environment variables for production security

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', 'AKIAUMYCIPB4ZB27WH57')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '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')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'chronoment')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-north-1')

# Set default ACL to None for private uploads (recommended for user content).
# This means files will NOT be publicly readable by default.
AWS_DEFAULT_ACL = None 

# Don't overwrite files with the same name. Django will append a unique string.
AWS_S3_FILE_OVERWRITE = False

# Set the default file storage to S3Boto3Storage from django-storages
# This is the critical setting that tells Django to use S3 for FileField/ImageField.
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# MEDIA_URL will now be used by Django to construct URLs for FileField/ImageField.
# These URLs will need to be pre-signed to be accessible.
MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/'


# Production logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    
}
